name: CI

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:


jobs:
  flatpak:
    name: "Flatpak CI"
    runs-on: ubuntu-latest
    strategy:
        matrix:
          config:
            - package: DaVinci Resolve
              file: Resolve 
              key: davinci-resolve
            - package: DaVinci Resolve Studio
              file: ResolveStudio
              key: davinci-resolve-studio

    container:
      image: ghcr.io/flathub-infra/flatpak-github-actions:freedesktop-25.08
      options: --privileged
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - uses: flatpak/flatpak-github-actions/flatpak-builder@v6.8
      with:
        bundle: ${{ matrix.config.key }}.flatpak
        build-debug-bundle: false
        manifest-path: com.blackmagic.${{ matrix.config.file }}.yaml
        cache-key: flatpak-builder-${{ matrix.config.key }}-${{ github.sha }}
        upload-artifact: true
        artifact-name: ${{ matrix.config.key }}.flatpak
