"""Udev rules management for DaVinci Resolve."""

import sys
from pathlib import Path

import config


def print_udev_rules(prefix: Path = None) -> None:
    """Print udev rules as a shell script for host system installation.
    
    Checks if DaVinci Resolve is installed, then prints a shell script
    that will recreate the udev rules files under /etc/udev/rules.d/.
    
    Args:
        prefix: Installation prefix path (default: config.INSTALL_PREFIX)
    """
    if prefix is None:
        prefix = config.INSTALL_PREFIX
    prefix = Path(prefix)
    udev_dir = prefix / "lib" / "udev" / "rules.d"
    
    # Check if Resolve is installed
    if not udev_dir.exists():
        print(f"Error: DaVinci Resolve is not installed at {prefix}", file=sys.stderr)
        print("Please install DaVinci Resolve first.", file=sys.stderr)
        sys.exit(1)
    
    # Find all .rules files
    rules_files = sorted(udev_dir.glob("*.rules"))
    
    if not rules_files:
        print(f"Error: No udev rules found in {udev_dir}", file=sys.stderr)
        sys.exit(1)
    
    # Print shell script header
    print("#!/bin/sh")
    print("# DaVinci Resolve udev rules installation script")
    print("# Generated by: flatpak run com.blackmagic.Resolve --print-udev-rules")
    print("#")
    print("# This script installs udev rules for DaVinci Resolve hardware devices.")
    print("# Run with: flatpak run com.blackmagic.Resolve --print-udev-rules | sudo sh")
    print()
    print("set -e")
    print()
    print("# Create udev rules directory")
    print("mkdir -p /etc/udev/rules.d")
    print()
    
    # Print each rules file
    for rules_file in rules_files:
        print(f"# Installing {rules_file.name}")
        print(f"cat > /etc/udev/rules.d/{rules_file.name} << 'EOF'")
        print(rules_file.read_text(), end="")
        print("EOF")
        print()
    
    # Print reload instructions
    print("# Reload udev rules")
    print("udevadm control --reload-rules")
    print("udevadm trigger")
    print()
    print("echo 'Udev rules installed successfully.'")
